y_MPC = out.y_MPC.Data;
y_MPC_TP = squeeze(y_MPC(1,:,:));
y_MPC_FP = squeeze(y_MPC(2,:,:));
y_MPC_FN = squeeze(y_MPC(3,:,:));
y_MPC_TN = squeeze(y_MPC(4,:,:));

y = out.y.Data;
y_TP = squeeze(out.y.Data(1,:,:));
y_FP= squeeze(out.y.Data(2,:,:));
y_FN= squeeze(out.y.Data(3,:,:));
y_TN = squeeze(out.y.Data(4,:,:));
r_MPC = out.r_s_MPC.Data;
r = out.r.Data;
r_MPC_P = squeeze(r_MPC(1,:,:));
r_MPC_N = squeeze(r_MPC(2,:,:));
r_P = squeeze(r(:,1))';
r_N = squeeze(r(:,2))';

% r_for_p = squeeze(out.r_s_for.Data(1,:,:));
% r_for_n = squeeze(out.r_s_for.Data(2,:,:));
% r_sn_t = out.r_sn_simulation.Time;
% y_TP = squeeze(out.y_p.Data(:,1));
% y_FP = squeeze(out.y_p.Data(:,2));
% y_FN = squeeze(out.y_n.Data(:,1));
% y_TN = squeeze(out.y_n.Data(:,2));
% y_TP_F = squeeze(out.y_rueck_TP.Data);
% y_FP_F= squeeze(out.y_rueck_FP.Data);
% y_FN_F= squeeze(out.y_rueck_FN.Data);
% y_TN_F = squeeze(out.y_rueck_TN.Data);